#!/usr/bin/env ruby

require 'yaml'
require 'aws-sdk'
require 'colorize'

def launch_db
  config = Hash[YAML.load(File.read('data/database_config.yml')).map{|(k,v)| [k.to_sym,v]}]
  client = Aws::RDS::Client.new(region: 'us-west-1')
  client.create_db_instance(config)

  db = Aws::RDS::DBInstance.new(config[:db_instance_identifier], client: client)
  db.wait_until(max_attempts: 10, delay: 90, interval: 15) do |i|
    i.db_instance_status == 'available'
  end
  db
end

db = launch_db
STDERR.puts "Successfully created staging database.\n".colorize(:green)
