#!/usr/bin/env ruby

require 'yaml'
require 'aws-sdk'
require 'colorize'

def destroy_db
  config = Hash[YAML.load(File.read('data/database_config.yml')).map{|(k,v)| [k.to_sym,v]}]
  client = Aws::RDS::Client.new(region: 'us-west-1')

  db = Aws::RDS::DBInstance.new(config[:db_instance_identifier], client: client)
  db.delete(skip_final_snapshot: true)
end

destroy_db
STDERR.puts "Successfully destroyed staging database.\n".colorize(:green)
